name: CI

on:
  push:
  pull_request:

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-version: '8.1'
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          ini-file: development
          tools: composer:v2
          coverage: none

      - name: "Install composer dependencies"
        run: |
          composer install

      # @todo execute unit tests

  functional-tests:
    name: functional-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-version: '8.1'
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          ini-file: development
          tools: composer:v2
          coverage: none

      - name: "Install composer dependencies"
        run: |
          composer install

      # @todo execute functional tests with sqlite
